[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Servidor IOT"
authors = [{name = "Ing. Electronico Especialista Ing. de Software", email = "pyptec@hotmail.com"}]
dynamic = ["version", "description"]
